/*
   ARCHIVO: creabase.sql
   AUTOR: Equipo Club Deportivo
   FECHA: 27/Nov/2025
   DESCRIPCION: Script DDL que crea nuestra base de datos. 
  
*/

CREATE DATABASE ClubDeportivo;
GO
USE ClubDeportivo;
GO

-- Esquema para la gestión de personas y accesos
CREATE SCHEMA MEMBRESIA
GO

-- Esquema para la gestión operativa, inventarios y finanzas
CREATE SCHEMA OPERACION
GO


-- TABLA 1: USUARIO_WEB
-- Descripción: Tabla padre que almacena credenciales y datos generales.
-- Consideración: Uso de IDENTITY (Llave Artificial) y UNIQUE.
CREATE TABLE MEMBRESIA.USUARIO_WEB (
    ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO_P VARCHAR(50) NOT NULL,
    APELLIDO_M VARCHAR(50),
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    COLONIA VARCHAR(100) NOT NULL,
    ALCALDIA VARCHAR(100) NOT NULL,
    USUARIO VARCHAR(50) UNIQUE NOT NULL, -- Restricción UNIQUE
    CONTRASEÑA VARCHAR (100) NOT NULL, 
    FECHA_REGISTRO DATETIME DEFAULT GETDATE() -- Valor por DEFAULT 
);




ALTER TABLE MEMBRESIA.USUARIO_WEB
ADD TIPO_USUARIO CHAR(1) NOT NULL;
    
ALTER TABLE MEMBRESIA.USUARIO_WEB
WITH CHECK ADD CONSTRAINT CK_TipoUsuario CHECK (TIPO_USUARIO IN ('S', 'E'));
GO


-- TABLA 2: SOCIO
-- Descripción: Subtipo de usuario. Maneja datos específicos de membresía.
-- Reglas: Validación de edad, tipo de membresía y estatus.
CREATE TABLE MEMBRESIA.SOCIO (
    ID_USUARIO INT PRIMARY KEY,
    NUM_SOCIO INT UNIQUE NOT NULL, -- Identificador alterno único
    TIPO_MEMBRESIA CHAR(1) NOT NULL, 
    FECHA_SOCIO DATE DEFAULT GETDATE(),
    IMAGEN_SOCIO VARBINARY(MAX),
    FECHA_NACIMIENTO DATE,
    ESTADO_SOCIO CHAR(1) NOT NULL,
    SEXO CHAR(1),
    PESO DECIMAL(5,2),
    ESTATURA DECIMAL(5,2),
    EDAD AS DATEDIFF(YEAR, FECHA_NACIMIENTO, GETDATE()), -- Columna Calculada
    
    CONSTRAINT FK_Socio_Usuario FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.USUARIO_WEB(ID_USUARIO),
    -- Validación de Dominio (Check Constraints)
    CONSTRAINT CK_Membresia CHECK (TIPO_MEMBRESIA IN ('V', 'E')), -- V=VIP, E=Estándar
    CONSTRAINT CK_EstadoSocio CHECK (ESTADO_SOCIO IN ('A', 'C')), -- A=Adeudo, C=Corriente

    CONSTRAINT CK_EdadMinimaSocio CHECK (DATEDIFF(YEAR, FECHA_NACIMIENTO, GETDATE()) >= 16)
);


CREATE TABLE MEMBRESIA.TIPO_MEMBRESIA (
    TIPO_MEMBRESIA CHAR(1) PRIMARY KEY,  -- 'V' o 'E'
    NOMBRE VARCHAR(50),
    COSTO DECIMAL(10,2) NOT NULL
);

ALTER TABLE MEMBRESIA.SOCIO
ADD CONSTRAINT FK_Membresia_Tipo
FOREIGN KEY (TIPO_MEMBRESIA)
REFERENCES MEMBRESIA.TIPO_MEMBRESIA(TIPO_MEMBRESIA);




-- TABLA 3: EMPLEADO
-- Descripción: Subtipo de usuario para personal del club.
CREATE TABLE MEMBRESIA.EMPLEADO (
    ID_USUARIO INT PRIMARY KEY,
    NSS CHAR(11) UNIQUE NOT NULL, -- Llave candidata
    TIPO_EMPLEADO CHAR(5),
    FECHA_INGRESO DATE DEFAULT GETDATE(),
    PUESTO VARCHAR(50),
    SUELDO DECIMAL(10,2),
    FECHA_CUMPLEAÑOS DATE,
    CONSTRAINT FK_Empleado_Usuario FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.USUARIO_WEB(ID_USUARIO)
);

-- TABLA 4: SOCIO_TELEFONO
-- Descripción: Tabla multivaluada para teléfonos.
CREATE TABLE MEMBRESIA.SOCIO_TELEFONO (
    ID_USUARIO INT,
    TELEFONO VARCHAR(20),
    PRIMARY KEY (ID_USUARIO, TELEFONO),
    CONSTRAINT FK_Tel_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO)
);

-- TABLA 5: SOCIO_CORREO
-- Descripción: Tabla multivaluada para correos.
CREATE TABLE MEMBRESIA.SOCIO_CORREO (
    ID_USUARIO INT,
    CORREO VARCHAR(100),
    PRIMARY KEY (ID_USUARIO, CORREO),
    CONSTRAINT FK_Correo_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO)
);

-- TABLA 6: SOCIO_FAMILIAR
-- Descripción: Relación recursiva.
CREATE TABLE MEMBRESIA.SOCIO_FAMILIAR (
    ID_USUARIO INT,
    ID_SOCIO_FAMILIAR INT,
    PARENTESCO VARCHAR(40),
    PRIMARY KEY (ID_USUARIO, ID_SOCIO_FAMILIAR),
    CONSTRAINT FK_Fam_Main FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO),
    CONSTRAINT FK_Fam_Rel FOREIGN KEY (ID_SOCIO_FAMILIAR) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO)
);

-- =================================================================================
--                              ESQUEMA OPERACION (16 Tablas)
-- =================================================================================

-- TABLA 7: EJERCICIO
-- Descripción: Catálogo de ejercicios para entrenamientos.
CREATE TABLE OPERACION.EJERCICIO (
    ID_EJERCICIO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    TIPO_EJERCICIO VARCHAR(30),
    ZONA_CORPORAL VARCHAR(30),
    SERIES_RECOMENDADAS INT
);

-- TABLA 8: PLATILLO
-- Descripción: Catálogo de alimentos para dietas.
CREATE TABLE OPERACION.PLATILLO (
    ID_PLATILLO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50),
    DESCRIPCION_PREPARACION VARCHAR(MAX),
    CALORIAS_POR_RACION INT,
    HORARIO_COMIDA CHAR(2), 
    TIPO_DIETA VARCHAR(20),
    CONSTRAINT CK_Horario_Comida CHECK (HORARIO_COMIDA IN ('D', 'M', 'CO', 'CE')) -- CS9
);

-- TABLA 9: INSTALACION
-- Descripción: Catálogo de instalaciones.
CREATE TABLE OPERACION.INSTALACION (
    ID_INSTALACION VARCHAR(20) PRIMARY KEY,
    NOMBRE_INSTALACION VARCHAR(100) NOT NULL,
    CAPACIDAD INT,
    DESCRIPCION VARCHAR(MAX)
);

-- TABLA 10: MATERIAL
-- Descripción: Catálogo global de materiales.
CREATE TABLE OPERACION.MATERIAL (
    ID_MATERIAL VARCHAR(20) PRIMARY KEY, 
    DESCRIPCION VARCHAR(50),
    UNIDADES_TOTALES INT
);

-- TABLA 11: DIETA
-- Descripción: Asignación de dietas a usuarios.
CREATE TABLE OPERACION.DIETA (
    ID_DIETA INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT,
    ID_PLATILLO INT,
    DIA_SEMANA VARCHAR(15),
    CALORIAS_TOTALES INT,
    CONSTRAINT FK_Dieta_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO),
    CONSTRAINT FK_Dieta_Plat FOREIGN KEY (ID_PLATILLO) REFERENCES OPERACION.PLATILLO(ID_PLATILLO)
);

-- TABLA 12: SERVICIOS_ACTIVIDADES
-- Descripción: Catálogo de clases y servicios.
-- Regla: Edad mínima por default 16 años.
CREATE TABLE OPERACION.SERVICIOS_ACTIVIDADES (
    ID_SERVICIO_ACTIVIDAD INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ACTIVIDAD VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(MAX),
    TIPO_ACTIVIDAD VARCHAR(20), 
    
    -- Consideración: Uso de VALOR POR DEFAULT
    EDAD_MINIMA INT DEFAULT 16, 
    
    CONSTRAINT CK_TipoActividad CHECK (TIPO_ACTIVIDAD IN ('CUOTA', 'GRATUITA', 'CULTURAL')),
    CONSTRAINT CK_EdadMinimaActividad CHECK (EDAD_MINIMA >= 16)
);



-- TABLA 13: CUOTA
-- Descripción: Subtipo de actividad que requiere pago.
CREATE TABLE OPERACION.CUOTA (
    ID_SERVICIO_ACTIVIDAD INT PRIMARY KEY,
    COSTO DECIMAL(10,2),
    METODO_PAGO CHAR(1),
    CONSTRAINT FK_Cuota_Serv FOREIGN KEY (ID_SERVICIO_ACTIVIDAD) REFERENCES OPERACION.SERVICIOS_ACTIVIDADES(ID_SERVICIO_ACTIVIDAD),
    CONSTRAINT CK_MetodoPagoCuota CHECK (METODO_PAGO IN ('T', 'E'))
);

-- TABLA 14: GRATUITAS
-- Descripción: Subtipo de actividad gratuita.
CREATE TABLE OPERACION.GRATUITAS (
    ID_SERVICIO_ACTIVIDAD INT PRIMARY KEY,
    ES_CULTURAL BIT,
    CONSTRAINT FK_Grat_Serv FOREIGN KEY (ID_SERVICIO_ACTIVIDAD) REFERENCES OPERACION.SERVICIOS_ACTIVIDADES(ID_SERVICIO_ACTIVIDAD)
);

-- TABLA 15: EMPLEADO_SERVICIO.
CREATE TABLE OPERACION.EMPLEADO_SERVICIO (
    ID_USUARIO INT,
    ID_SERVICIO_ACTIVIDAD INT,
    NOMBRE_EMPLEADO VARCHAR(100), 
    PRIMARY KEY (ID_USUARIO, ID_SERVICIO_ACTIVIDAD),
    CONSTRAINT FK_ES_Emp FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.EMPLEADO(ID_USUARIO),
    CONSTRAINT FK_ES_Serv FOREIGN KEY (ID_SERVICIO_ACTIVIDAD) REFERENCES OPERACION.SERVICIOS_ACTIVIDADES(ID_SERVICIO_ACTIVIDAD)
);

-- TABLA 16: HORARIO
-- Descripción: Malla de horarios.
CREATE TABLE OPERACION.HORARIO (
    ID_HORARIO INT PRIMARY KEY IDENTITY(1,1),
    ID_SERVICIO_ACTIVIDAD INT,
    ID_INSTALACION VARCHAR(20),
    ID_PROFESOR INT, 
    DIA_SEMANA VARCHAR(15),
    HORA_INICIO TIME,
    HORA_FIN TIME,
    CONSTRAINT FK_Hor_Act FOREIGN KEY (ID_SERVICIO_ACTIVIDAD) REFERENCES OPERACION.SERVICIOS_ACTIVIDADES(ID_SERVICIO_ACTIVIDAD),
    CONSTRAINT FK_Hor_Inst FOREIGN KEY (ID_INSTALACION) REFERENCES OPERACION.INSTALACION(ID_INSTALACION),
    CONSTRAINT FK_Hor_Prof FOREIGN KEY (ID_PROFESOR) REFERENCES MEMBRESIA.EMPLEADO(ID_USUARIO)
);

-- TABLA 17: ENTRENAMIENTO
-- Descripción: Cabecera del plan de entrenamiento del socio.
CREATE TABLE OPERACION.ENTRENAMIENTO (
    ID_ENTRENAMIENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT,
    DIA_SEMANA VARCHAR(15),
    HORA_INICIO TIME,
    DURACION_MINUTOS INT,
    CONSTRAINT FK_Entreno_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO)
);

-- TABLA 18: EJERCICIO_ENTRENAMIENTO
-- Descripción: Detalle del plan (ejercicios específicos).
CREATE TABLE OPERACION.EJERCICIO_ENTRENAMIENTO (
    ID_ENTRENAMIENTO INT,
    ID_EJERCICIO INT,
    SERIES_REALES INT,
    REPETICIONES INT,
    PRIMARY KEY (ID_ENTRENAMIENTO, ID_EJERCICIO),
    CONSTRAINT FK_EE_Plan FOREIGN KEY (ID_ENTRENAMIENTO) REFERENCES OPERACION.ENTRENAMIENTO(ID_ENTRENAMIENTO),
    CONSTRAINT FK_EE_Ejer FOREIGN KEY (ID_EJERCICIO) REFERENCES OPERACION.EJERCICIO(ID_EJERCICIO)
);

-- TABLA 19: INSCRIPCION
-- Descripción: Registro de un socio a una clase en un horario.
CREATE TABLE OPERACION.INSCRIPCION (
    ID_INSCRIPCION INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT,
    ID_HORARIO INT,
    FECHA_INSCRIPCION DATETIME DEFAULT GETDATE(),
    ESTADO_INSCRIPCION VARCHAR(15) NOT NULL, 
    CONSTRAINT FK_Ins_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO),
    CONSTRAINT FK_Ins_Horario FOREIGN KEY (ID_HORARIO) REFERENCES OPERACION.HORARIO(ID_HORARIO),
    CONSTRAINT CK_EstadoIns CHECK (ESTADO_INSCRIPCION IN ('SOLICITADA', 'PAGADA', 'CANCELADA'))
);

-- TABLA 20: ALQUILER
-- Descripción: Reservación de espacios físicos y materiales.
CREATE TABLE OPERACION.ALQUILER (
    ID_RESERVACION INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT NOT NULL,
    ID_INSTALACION VARCHAR(20) NOT NULL,
    ID_MATERIAL VARCHAR(20) NULL,
    FECHA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    NUMERO_PERSONAS INT,
    ESTADO_ALQUILER VARCHAR(20) NOT NULL, 
    CONSTRAINT FK_Alq_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO),
    CONSTRAINT FK_Alq_Inst FOREIGN KEY (ID_INSTALACION) REFERENCES OPERACION.INSTALACION(ID_INSTALACION),
    CONSTRAINT FK_Alq_Mat FOREIGN KEY (ID_MATERIAL) REFERENCES OPERACION.MATERIAL(ID_MATERIAL),
    CONSTRAINT CK_EstadoAlq CHECK (ESTADO_ALQUILER IN ('SOLICITADO', 'ENTREGADO', 'DEVUELTO', 'DAÑADO', 'NO_ASISTIO'))
);


-- TABLA 21: PAGOS
-- Descripción: Registro financiero.
CREATE TABLE OPERACION.PAGOS (
    ID_PAGO INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT,
    ID_INSCRIPCION INT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA_PAGO DATE DEFAULT GETDATE(),
    METODO_PAGO VARCHAR(20),
    BANCO VARCHAR(50),
    NUM_TARJETA VARCHAR(20),
    VIGENCIA_MES INT,
    VIGENCIA_ANIO INT,
    TIPO_CONCEPTO VARCHAR(20),
    CONSTRAINT FK_Pago_Socio FOREIGN KEY (ID_USUARIO) REFERENCES MEMBRESIA.SOCIO(ID_USUARIO),
    CONSTRAINT FK_Pago_Ins FOREIGN KEY (ID_INSCRIPCION) REFERENCES OPERACION.INSCRIPCION(ID_INSCRIPCION),
    
    CONSTRAINT CK_FechaPago CHECK (DAY(FECHA_PAGO) <= 5)
);

ALTER TABLE OPERACION.PAGOS 
DROP CONSTRAINT CK_FechaPago;


select * from OPERACION.PAGOS
order by ID_USUARIO
-- TABLA 22: MATERIAL_INSTALACION
-- Descripción: Control de inventario distribuido.
CREATE TABLE OPERACION.MATERIAL_INSTALACION (
    ID_INSTALACION VARCHAR(20),
    ID_MATERIAL VARCHAR(20),
    UNIDADES_EN_SITIO INT,
    PRIMARY KEY (ID_INSTALACION, ID_MATERIAL),
    CONSTRAINT FK_MI_Inst FOREIGN KEY (ID_INSTALACION) REFERENCES OPERACION.INSTALACION(ID_INSTALACION),
    CONSTRAINT FK_MI_Mat FOREIGN KEY (ID_MATERIAL) REFERENCES OPERACION.MATERIAL(ID_MATERIAL)
);
GO



CREATE NONCLUSTERED INDEX IX_Usuario_Nombre ON MEMBRESIA.USUARIO_WEB (NOMBRE, APELLIDO_P);
CREATE NONCLUSTERED INDEX IX_Socio_Num ON MEMBRESIA.SOCIO (NUM_SOCIO);
CREATE NONCLUSTERED INDEX IX_Alquiler_Fecha ON OPERACION.ALQUILER (FECHA);
CREATE NONCLUSTERED INDEX IX_Pagos_Usuario ON OPERACION.PAGOS (ID_USUARIO);
CREATE UNIQUE INDEX IX_Correo_Unico ON MEMBRESIA.SOCIO_CORREO (CORREO);
GO





