/*
   ARCHIVO: seguridad.sql
   AUTOR: Equipo Club Deportivo
   FECHA: 28/Nov/2025
   DESCRIPCION: Script DCL para la gestión de seguridad.
                - Implementa los 2 Roles: SOCIO y EMPLEADO.
                - Procedimiento para crear usuarios y asignarles su rol.
*/

USE ClubDeportivo;
GO


/* ========================================
   1. CREACIÓN DE ROLES
   ======================================== */
CREATE ROLE ROL_SOCIO;
CREATE ROLE ROL_EMPLEADO;
GO

/* ========================================
   2. CREACIÓN DE USUARIOS / LOGINS
   ======================================== */

-- Diego (Empleado/Admin)
CREATE LOGIN diegoAdmin WITH PASSWORD = N'Diego123!', DEFAULT_DATABASE = [ClubDeportivo], CHECK_EXPIRATION = OFF;
GO
CREATE USER diegoAdmin FOR LOGIN diegoAdmin;
GO
ALTER ROLE ROL_EMPLEADO ADD MEMBER diegoAdmin;
GO

-- Carlos (Empleado/Admin)
CREATE LOGIN carlosAdmin WITH PASSWORD = N'Carlos123!', DEFAULT_DATABASE = [ClubDeportivo], CHECK_EXPIRATION = OFF;
GO
CREATE USER carlosAdmin FOR LOGIN carlosAdmin;
GO
ALTER ROLE ROL_EMPLEADO ADD MEMBER carlosAdmin;
GO

-- Diego2 (Empleado/Admin)
CREATE LOGIN diego2Socio WITH PASSWORD = N'Diego2123!', DEFAULT_DATABASE = [ClubDeportivo], CHECK_EXPIRATION = OFF;
GO
CREATE USER diego2Socio FOR LOGIN diego2Socio;
GO
ALTER ROLE ROL_Socio ADD MEMBER diego2Socio;
GO

-- MarthaMaestra (Empleado/Admin)
CREATE LOGIN MarthaMaestra WITH PASSWORD = N'Martha123!', DEFAULT_DATABASE = [ClubDeportivo], CHECK_EXPIRATION = OFF;
GO
CREATE USER MarthaMaestra FOR LOGIN MarthaMaestra;
GO
ALTER ROLE ROL_EMPLEADO ADD MEMBER MarthaMaestra;
GO

/* ========================================
   3. OTORGAR PERMISOS A LOS ROLES
   ======================================== */

-- ---------- PERMISOS DE LECTURA ----------
GRANT SELECT ON MEMBRESIA.USUARIO_WEB TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON MEMBRESIA.SOCIO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON MEMBRESIA.EMPLEADO TO ROL_EMPLEADO;
GRANT SELECT ON MEMBRESIA.SOCIO_TELEFONO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON MEMBRESIA.SOCIO_CORREO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON MEMBRESIA.SOCIO_FAMILIAR TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.EJERCICIO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.PLATILLO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.INSTALACION TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.MATERIAL TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.DIETA TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.SERVICIOS_ACTIVIDADES TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.CUOTA TO ROL_EMPLEADO;
GRANT SELECT ON OPERACION.GRATUITAS TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.EMPLEADO_SERVICIO TO ROL_EMPLEADO;
GRANT SELECT ON OPERACION.HORARIO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.ENTRENAMIENTO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.EJERCICIO_ENTRENAMIENTO TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.INSCRIPCION TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.ALQUILER TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.PAGOS TO ROL_SOCIO, ROL_EMPLEADO;
GRANT SELECT ON OPERACION.MATERIAL_INSTALACION TO ROL_EMPLEADO;
GO

-- ---------- PERMISOS DE INSERTAR ----------
GRANT INSERT ON MEMBRESIA.SOCIO TO ROL_SOCIO;
GRANT INSERT ON MEMBRESIA.EMPLEADO TO ROL_EMPLEADO;
GRANT INSERT ON OPERACION.SERVICIOS_ACTIVIDADES TO ROL_EMPLEADO;
GRANT INSERT ON OPERACION.CUOTA TO ROL_EMPLEADO;
GRANT INSERT ON OPERACION.GRATUITAS TO ROL_EMPLEADO;
GRANT INSERT ON OPERACION.INSCRIPCION TO ROL_SOCIO;
GRANT INSERT ON OPERACION.ALQUILER TO ROL_SOCIO;
GRANT INSERT ON OPERACION.PAGOS TO ROL_SOCIO;
GO

-- ---------- PERMISOS DE ACTUALIZAR ----------
GRANT UPDATE ON MEMBRESIA.SOCIO TO ROL_SOCIO;
GRANT UPDATE ON MEMBRESIA.EMPLEADO TO ROL_EMPLEADO;
GRANT UPDATE ON OPERACION.SERVICIOS_ACTIVIDADES TO ROL_EMPLEADO;
GRANT UPDATE ON OPERACION.CUOTA TO ROL_EMPLEADO;
GRANT UPDATE ON OPERACION.INSCRIPCION TO ROL_SOCIO;
GRANT UPDATE ON OPERACION.ALQUILER TO ROL_SOCIO;
GO

-- ---------- PERMISOS DE ELIMINAR ----------
GRANT DELETE ON MEMBRESIA.SOCIO TO ROL_EMPLEADO;
GRANT DELETE ON MEMBRESIA.EMPLEADO TO ROL_EMPLEADO;
GRANT DELETE ON OPERACION.SERVICIOS_ACTIVIDADES TO ROL_EMPLEADO;
GRANT DELETE ON OPERACION.CUOTA TO ROL_EMPLEADO;
GRANT DELETE ON OPERACION.INSCRIPCION TO ROL_EMPLEADO;
GRANT DELETE ON OPERACION.ALQUILER TO ROL_EMPLEADO;
GRANT DELETE ON OPERACION.PAGOS TO ROL_EMPLEADO;
GO

-- ---------- PERMISOS ESPECIALES AL ROL_EMPLEADO ----------
GRANT ALTER ANY USER TO ROL_EMPLEADO;
GRANT ALTER ANY ROLE TO ROL_EMPLEADO;
GRANT CREATE PROCEDURE TO ROL_EMPLEADO;
GO


